namePrefix: dev-  

commonLabels:
  variant: development

commonAnnotations:
  # note: We are on dev now
  stage: development

resources:
  - ../../base

patchesStrategicMerge:
#  - deployment.yaml
  - route.yaml